# Generated by Django 2.2.10 on 2020-02-13 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_investment', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=10, max_digits=19)),
                ('purchase_date', models.DateTimeField(verbose_name='purchase date')),
            ],
        ),
    ]
