# Generated by Django 2.2.10 on 2020-02-13 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteiraapp', '0002_auto_20200213_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='type_investment',
            field=models.CharField(choices=[('Fixed', 'Fixed'), ('Variable', 'Variable')], max_length=200),
        ),
    ]
