# Generated by Django 2.2.10 on 2020-02-14 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteiraapp', '0003_auto_20200213_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
        migrations.AlterField(
            model_name='investment',
            name='type_investment',
            field=models.CharField(choices=[('Fixo', 'Fixo'), ('Variável', 'Variável')], max_length=200),
        ),
    ]
