# Generated by Django 2.2.10 on 2020-02-14 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteiraapp', '0005_auto_20200214_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='purchase_date',
            field=models.DateTimeField(verbose_name='purchase date'),
        ),
    ]
