# Generated by Django 2.2.10 on 2020-02-14 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteiraapp', '0008_auto_20200214_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='purchase_date',
            field=models.DateField(),
        ),
    ]
